var mlJob = document.getElementById("mlJob");
var overview = document.getElementById("overview");
var qualifications = document.getElementById("qualifications");
var salary = document.getElementById("salary");
overview.onclick = function() {
    mlJob.innerHTML = '<h3>Average Day</h3><div class="sideImg"><img src="https://codeop.tech/wp-content/uploads/2022/09/women-in-coding-e1664430458975.jpg"><ul><li>Ensure automation and AI software models work properly</li><li>In charge of making sure all repeatable tasks work properly and efficiently</li><li>Add new functionalities to existing processes</li><li>Configure, execute, and verify data collected in system for accuracy</li><li>Ensure everything runs smoothly on daily basis</li></ul></div><h3>Work Environment</h3><div class="sideImg"><ul><li><b>Hybrid:</b> Employees are allowed to decide whether they want to work at office or from home, and most meetings will be through Zoom</li><li><b>Part-time or full-time:</b> 20-40 hours per week minimum, no upper limit, 7 am - 4 pm PT</li></ul><img src="https://thehill.com/wp-content/uploads/sites/2/2020/05/ca_zoommeeting_051420istock.jpg"></div><h3>Team Structure</h3><p3 style="font-weight: normal">Machine learning software architects work alongside a <b>team</b> of people to develop large language models.</p3><div class="sideImg" style="padding-top: 30px"><img src="https://www.datocms-assets.com/23428/1690463625-teamwork-hi-five-1.jpg"><ul><li>Software engineers</li><li>Data scientists</li><li>AI specialists</li></ul></div><h3>Potential Challenges</h3><div class="sideImg"><ul><li>Competing against other coworkers and people working in the same career</li><li>Encountering and fixing bugs in code for AI models</li></ul><img src="https://res.cloudinary.com/practicaldev/image/fetch/s--TxGQd5YU--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://thepracticaldev.s3.amazonaws.com/i/qrbwfvu270ucauwk4xfn.png"></div><h3>Ideal Candidate</h3><div class="sideImg"><img src="softSkills.png" class="smaller"><ul><li>Thought leadership (AI-driven mindset while dealing AI-associated risks)</li><li>Strategic thinking</li><li>Collaboration</li><li>Problem-solving</li><li>Flexibility</li><li>Time management</li><li>Communication</li></ul></div><div class="sideImg"><ul><li>Programming (Python, Java)</li><li>Software engineering (DevOps workflows and tools)</li><li>Analytics</li><li>Applied mathematics</li></ul><img src="hardSkills.png" class="smaller"></div><div class="sideImg"><img src="personality.png" class="smaller"><ul><li>Hard working</li><li>Responsible</li><li>Creative</li><li>Empathetic</li></ul></div>';
}
qualifications.onclick = function() {
    mlJob.innerHTML = '<p>Qualifications<p>';
}
salary.onclick = function() {
    mlJob.innerHTML = '<p>Salary<p>';
}