var mlJob = document.getElementById("mlJob");
var overview = document.getElementById("overview");
var qualifications = document.getElementById("qualifications");
var comparisons = document.getElementById("comparisons");
overview.onclick = function() {
    mlJob.innerHTML = '<h3>Average Day</h3><div class="sideImg"><img src="https://codeop.tech/wp-content/uploads/2022/09/women-in-coding-e1664430458975.jpg"><ul><li>Ensure automation and AI software models work properly</li><li>In charge of making sure all repeatable tasks work properly and efficiently</li><li>Add new functionalities to existing processes</li><li>Configure, execute, and verify data collected in system for accuracy</li><li>Ensure everything runs smoothly on daily basis</li></ul></div><h3>Work Environment</h3><div class="sideImg"><ul><li><b>Hybrid:</b> Employees are allowed to decide whether they want to work at office or from home, and most meetings will be through Zoom</li><li><b>Part-time or full-time:</b> 20-40 hours per week minimum, no upper limit, 7 am - 4 pm PT</li></ul><img src="https://thehill.com/wp-content/uploads/sites/2/2020/05/ca_zoommeeting_051420istock.jpg"></div><h3>Team Structure</h3><p3 class="normal">Machine learning software architects work alongside a <b>team</b> of people to develop large language models.</p3><div class="sideImg" style="padding-top: 30px"><img src="https://www.datocms-assets.com/23428/1690463625-teamwork-hi-five-1.jpg"><ul><li>Software engineers</li><li>Data scientists</li><li>AI specialists</li></ul></div><h3>Potential Challenges</h3><div class="sideImg"><ul><li>Competing against other coworkers and people working in the same career</li><li>Encountering and fixing bugs in code for AI models</li></ul><img src="https://res.cloudinary.com/practicaldev/image/fetch/s--TxGQd5YU--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://thepracticaldev.s3.amazonaws.com/i/qrbwfvu270ucauwk4xfn.png"></div><h3>Ideal Candidate</h3><div class="sideImg"><img src="softSkills.png" class="smaller"><ul><li>Thought leadership (AI-driven mindset while dealing AI-associated risks)</li><li>Strategic thinking</li><li>Collaboration</li><li>Problem-solving</li><li>Flexibility</li><li>Time management</li><li>Communication</li></ul></div><div class="sideImg"><ul><li>Programming (Python, Java)</li><li>Software engineering (DevOps workflows and tools)</li><li>Analytics</li><li>Applied mathematics</li></ul><img src="hardSkills.png" class="smaller"></div><div class="sideImg"><img src="personality.png" class="smaller"><ul><li>Hard working</li><li>Responsible</li><li>Creative</li><li>Empathetic</li></ul></div>';
}
qualifications.onclick = function() {
    mlJob.innerHTML = '<h3>Requirements</h3><p3 class="normal">Machine learning software architects need a <b>Master&#39;s degree</b>, which usually takes <b>6 years</b> to complete, in one of the following majors:</p3><div class="sideImg topPad"><ul><li>Computer science</li><li>Mathematics</li><li>Computer and information research science</li><li>Data analytics</li><li>Similar majors</li></ul><img src="https://res.cloudinary.com/frame-destination/images/w_1200,h_628,c_scale/f_auto,q_auto/v1685657255/blog/What_Size_Diploma_Frame/What_Size_Diploma_Frame.jpg?_i=AA"></div><h3 style="padding-bottom: 10px; margin-bottom: 0px">Stanford University</h3><p class="uniTags" style="background-color: #480CA8">Challenging</p><div class="sideImg topPad"><img src="https://online.stanford.edu/sites/default/files/styles/front_intro_image_l/public/2023-10/stanford-online-background-image.jpg.webp?itok=zdPOrQ5A"><p3 class="normal">Stanford is one of the challenging universities we recommend for potential employees looking into joining ArisBots.</p></div><h3 style="padding-bottom: 10px; margin-bottom: 0px">University of California, San Diego</h3><p class="uniTags" style="background-color: #4361EE">Intermediate</p><div class="sideImg topPad"><img src="https://collegevine.imgix.net/13ea25b5-3b27-412c-8be5-1f7e0bded961.jpg"><p3 class="normal">UCSD is one of the intermediate universities we recommend for potential employees looking into joining ArisBots.</p></div><h3 style="padding-bottom: 10px; margin-bottom: 0px">California State Polytechnic University, Humboldt</h3><p class="uniTags" style="background-color: #B5179E">Lenient</p><div class="sideImg topPad"><img src="https://assets.simpleviewinc.com/simpleview/image/upload/c_limit,q_80,w_1200/v1/crm/eurekaca/Camp080916_0005-0-ac4030645056a36_ac4031ea-5056-a36a-0954ad1c52305b11.jpg"><p3 class="normal">Cal Poly Humboldt is one of the lenient universities we recommend for potential employees looking into joining ArisBots.</p></div><img src="admissionReqs.png"><img src="prereqCourses.png"><img src="costs.png">';
}
comparisons.onclick = function() {
    mlJob.innerHTML = '<img src="salaries.png"><img src="comparison.png"><h3>Recurring Expenses</h3><p3 class="normal">Machine learning software architects typically have to spend thousands of dollars during the development process of AI models.</p3><div class="sideImg topPad"><ul><li><b>Artificially generating training data (high quality):</b> $25,000 - $65,000</li><li><b>Cloud resources (virtual CPUs):</b> $1,460 - $3,600/year</li><li><b>Maintainance/support:</b> $20,000 - $150,000/year</li></ul><img src="https://static.vecteezy.com/system/resources/previews/009/260/535/non_2x/money-bag-on-wood-with-coins-stack-in-morning-light-concept-saving-free-photo.jpg"></div><h3>Job Outlook</h3><div class="sideImg"><ul><li>Among <b>top 5</b> IT jobs with highest demand <i>(Robert Half Salary Guide)</i></li><li><b>13% jump</b> in computer jobs predicted from 2016-2026 <i>(United States Bureau of Labor Statistics)</i></li><li>One of <b>fastest-growing</b> occupations in US <i>(Bureau of Labor Statistics)</i></li><li>Highly <b>competitive</b> among applicants and between companies</li></ul><img src="https://www.rxrelief.com/wp-content/uploads/sites/3/2019/01/ThinkstockPhotos-179333406-3.jpg"></div>';
}